# Generated by Django 2.1.7 on 2020-04-01 10:01

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('bryqm', models.CharField(blank=True, max_length=100, verbose_name='本人邀请码')),
                ('tryqm', models.CharField(blank=True, max_length=100, verbose_name='他人邀请码')),
                ('money', models.FloatField(default=0, verbose_name='金额')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ChongZhiInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='充值账户')),
                ('money', models.CharField(max_length=255, verbose_name='金额')),
                ('cz_status', models.BooleanField(default=False, verbose_name='充值状态')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '充值信息',
                'verbose_name_plural': '充值信息',
            },
        ),
        migrations.CreateModel(
            name='DingDanInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zyr', models.CharField(max_length=255, verbose_name='租用人')),
                ('fb_user', models.CharField(max_length=255, verbose_name='发布用户')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='标题')),
                ('game_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='游戏名称')),
                ('area', models.CharField(blank=True, max_length=255, null=True, verbose_name='区域')),
                ('server', models.CharField(blank=True, max_length=255, null=True, verbose_name='服务器')),
                ('money', models.CharField(blank=True, max_length=255, null=True, verbose_name='租金')),
                ('zh', models.CharField(blank=True, max_length=255, null=True, verbose_name='账号')),
                ('pwd', models.CharField(blank=True, max_length=255, null=True, verbose_name='密码')),
                ('hours', models.CharField(blank=True, max_length=255, null=True, verbose_name='小时')),
                ('zy_time', models.CharField(blank=True, max_length=255, null=True, verbose_name='租赁开始时间')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '订单信息',
                'verbose_name_plural': '订单信息',
            },
        ),
        migrations.CreateModel(
            name='FenLeiInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='分类名称')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '分类信息',
                'verbose_name_plural': '分类信息',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pt_name', models.CharField(max_length=255, verbose_name='平台名称')),
                ('phone', models.CharField(max_length=255, verbose_name='服务电话')),
                ('gg', models.CharField(max_length=255, verbose_name='后台公告')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '平台的其它信息',
                'verbose_name_plural': '平台的其它信息',
            },
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_user', models.CharField(max_length=255, verbose_name='消息用户')),
                ('message_content', models.CharField(max_length=1000, verbose_name='消息内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '用户消息信息',
                'verbose_name_plural': '用户消息信息',
            },
        ),
        migrations.CreateModel(
            name='ZuHao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_user', models.CharField(max_length=255, verbose_name='发布用户')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='标题')),
                ('game_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='游戏名称')),
                ('area', models.CharField(blank=True, max_length=255, null=True, verbose_name='区域')),
                ('server', models.CharField(blank=True, max_length=255, null=True, verbose_name='服务器')),
                ('money', models.CharField(blank=True, max_length=255, null=True, verbose_name='租金')),
                ('zh', models.CharField(blank=True, max_length=255, null=True, verbose_name='账号')),
                ('pwd', models.CharField(blank=True, max_length=255, null=True, verbose_name='密码')),
                ('fb_status', models.BooleanField(default=False, verbose_name='发布状态')),
                ('yz_status', models.BooleanField(default=False, verbose_name='租用状态')),
                ('hours', models.CharField(blank=True, max_length=255, null=True, verbose_name='租用小时数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('zy_time', models.CharField(blank=True, max_length=255, null=True, verbose_name='租赁时间')),
            ],
            options={
                'verbose_name': '本站租号信息',
                'verbose_name_plural': '本站租号信息',
            },
        ),
        migrations.CreateModel(
            name='ZuHaoWan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('game_name', models.CharField(max_length=255, verbose_name='游戏名称')),
                ('area', models.CharField(max_length=255, verbose_name='区域')),
                ('server', models.CharField(max_length=255, verbose_name='服务器')),
                ('money', models.CharField(max_length=255, verbose_name='租金')),
                ('url', models.CharField(max_length=255, verbose_name='链接')),
            ],
            options={
                'verbose_name': '外站租号信息',
                'verbose_name_plural': '外站租号信息',
                'db_table': 'zuhaowan',
            },
        ),
    ]
